name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verification-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification de la structure minimale
        run: |
          test -f README.md
          test -f Dockerfile
          test -f docs/architecture.md
          test -f docs/cahier-des-charges.md
          test -f scripts/provision/provision-local.ps1
          test -f scripts/verify/verify-local.ps1
          test -f terraform/main.tf